spring.application.name=chinook-api-spring
spring.datasource.url=jdbc:postgresql://localhost:5432/sample_data
spring.datasource.username=postgres
spring.datasource.password=1234

# WICHTIG: Bestehende Daten nur validieren, nicht ändern!
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
